Algoritmo "Exercicio3"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Vinicius Bayão Gomes
// Data atual  : 25/05/2020
Var
// Seção de Declarações das variáveis 
   C:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Para C <- 100 ate 200 passo+1 faca
        Escreval(C)
        Se (C%2<>0) entao
           Escreval("Número ímpar:",C)
        Fimse
   Fimpara

Fimalgoritmo