Algoritmo "Exercicio6"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/05/2020
Var
// Seção de Declarações das variáveis 
   valor,i:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Digite o valor a qual você deseja ver a tabuada: ")
   Leia(valor)
   
   Para i <- 1 ate 10 faca
        Escreval(valor, " X ", i," = ",valor * i)
   Fimpara

Fimalgoritmo