Algoritmo "Exercicio2"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Vinicius Bayão Gomes
// Data atual  : 25/05/2020
Var
// Seção de Declarações das variáveis 
c:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Para c <- 1 ate 100 passo+1 faca
        Escreval(c)
        Se (c%10=0) entao
           Escreval("Múltiplo de 10:",c)
        Fimse
   Fimpara

Fimalgoritmo