Algoritmo "Exercicio2"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Vinicius Bayão Gomes
// Data atual  : 25/05/2020
Var
// Seção de Declarações das variáveis 
   numero,a,b:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   Escreva("Digite um número: ")
   Leia(numero)
   
   Se (numero>0) entao
      a <- numero
      Escreval("a")
   Senao
        b <- numero
        Escreval("b")
   Fimse

Fimalgoritmo