Algoritmo "Exercicio1"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Vinicius Bayão Gomes
// Data atual  : 25/05/2020
Var
// Seção de Declarações das variáveis 
   n:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   Escreva("Digite um valor: ")
   Leia(n)
   
   Se (n>100) entao
      Escreval(n)
   Senao
        Escreval("n=0")
   Fimse

Fimalgoritmo