Algoritmo "Exercicio3"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Vinicius Bayão Gomes
// Data atual  : 25/05/2020
Var
// Seção de Declarações das variáveis 
   numero,p,i:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   Escreva("Digite um valor: ")
   Leia(numero)
   
   Se(numero%2=0) entao
      p <- numero
      Escreval("p")
   Senao
        i <- numero
        Escreval("i")
   Fimse

Fimalgoritmo