Algoritmo "Exercicio3"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    :
// Data atual  : 25/05/2020
Var
// Seção de Declarações das variáveis 
v:vetor[1..10] de inteiro
c:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Para c <- 1 ate 10 faca
        Escreva("Digite",c,"º valor: ")
        Leia(v[c])
   Fimpara
   
   Para c <- 10 ate 1 passo -1 faca
        Escreval(v[c])
   Fimpara

Fimalgoritmo