algoritmo "Exercicio3"
// =============================================================
//
//
// AUTOR: Vinicius Bayão
// Curso: Algoritmos e Lógica de Programação(Geek University)
// =============================================================
var
n1,n2,Soma:inteiro

inicio
      Escreva("Digite um número: ")
      Leia(n1)
      
      Escreva("Digite outro número: ")
      Leia(n2)
      
      Soma <- n1 + n2
      
      Escreval("A soma dos dois valores foi de:",Soma)

fimalgoritmo
