Algoritmo "Exercício7"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Vinicius Bayão Gomes
// Data atual  : 25/05/2020
Var
// Seção de Declarações das variáveis 
   altura,Peso_ideal:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   Escreva("Digite sua altura: ")
   Leia(altura)
   
   Peso_ideal <- (72.7 * altura) - 58
   
   Escreval("Seu peso ideal é de:",Peso_ideal," Kg")

Fimalgoritmo