Algoritmo "Exercício5"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Vinicius Bayão Gomes
// Data atual  : 25/05/2020
Var
// Seção de Declarações das variáveis 
   centimetros,metro:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Digite um valor em metros: ")
   Leia(metro)
   
   centimetros <- metro * 100
   
   Escreval("O valor ",metro," metros em centímetros é:",centimetros," cm")

Fimalgoritmo