algoritmo "Exercicio2"

//Feito por:Vinicius Bayão Gomes.
//
var
estoque_medio:real
quantidade_maxima:inteiro
quantidade_minima:inteiro
inicio
      Escreva("Digite a quantidade máxima de peças: ")
      Leia(quantidade_maxima)
      
      Escreva("Digite a quantidade mmínima de peças: ")
      Leia(quantidade_minima)
      
      estoque_medio <- (quantidade_maxima + quantidade_minima)/2
      
      Escreval("O estoque médio é de: ",estoque_medio:4:1)
      
fimalgoritmo